services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: vscode_python_slim
    ports:
      - "3000:3000"  
      - "8501:8501"  
    volumes:
      - .:/home/workspace
    environment:
      - PASSWORD=1  
    restart: always
